# Homework 3

In [56]:
import dalex as dx
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

from keras.models import Sequential
from keras.layers import Dense
import keras.backend as K

In [2]:
data = pd.read_csv('hotel_bookings.csv')
data.head()

hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July   
1  Resort Hotel            0        737               2015               July   
2  Resort Hotel            0          7               2015               July   
3  Resort Hotel            0         13               2015               July   
4  Resort Hotel            0         14               2015               July   

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1   
1                        27                          1   
2                        27                          1   
3                        27                          1   
4                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  deposit_type  \
0                        0                     0       2  ...    No Deposit   
1                        0                     0       2  ...    No Deposit   
2                        0                     1       1  ...    No Deposit   
3                        0                     1       1  ...    No Deposit   
4                        0                     2       2  ...    No Deposit   

   agent company days_in_waiting_list customer_type   adr  \
0    NaN     NaN                    0     Transient   0.0   
1    NaN     NaN                    0     Transient   0.0   
2    NaN     NaN                    0     Transient  75.0   
3  304.0     NaN                    0     Transient  75.0   
4  240.0     NaN                    0     Transient  98.0   

   required_car_parking_spaces  total_of_special_requests  reservation_status  \
0                            0                          0           Check-Out   
1                            0                          0           Check-Out   
2                            0                          0           Check-Out   
3                            0                          0           Check-Out   
4                            0                          1           Check-Out   

  reservation_status_date  
0              2015-07-01  
1              2015-07-01  
2              2015-07-02  
3              2015-07-02  
4              2015-07-03  

[5 rows x 32 columns]

In [3]:
# in order to simplify plots I decided to use only a subset of variables
data = data[['is_canceled', 'lead_time', 'arrival_date_year', 'adults', 'children', 'babies', 'booking_changes']]
data = data.dropna()
X, y = data.loc[:, data.columns != 'is_canceled'], data[['is_canceled']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

In [44]:
observation = pd.DataFrame({'lead_time': [203.0],
                       'arrival_date_year': [2016.0],
                       'adults': [2.0],
                       'children': [0.0],
                       'babies': [0.0],
                       'booking_changes': [4.]},
                      index = ['observation'])

## Neural network

In [36]:
def f1_metric(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
    predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
    precision = true_positives / (predicted_positives + K.epsilon())
    recall = true_positives / (possible_positives + K.epsilon())
    f1_val = 2*(precision*recall)/(precision+recall+K.epsilon())
    return f1_val

In [39]:
model = Sequential()
model.add(Dense(20, input_dim=6, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy', f1_metric])

In [40]:
model.fit(X_train, y_train, epochs=150, batch_size=10)

Epoch 1/150
10745/10745 [==============================] - 7s 681us/step - loss: 0.6242 - accuracy: 0.6447 - f1_metric: 0.1800
Epoch 2/150
10745/10745 [==============================] - 7s 611us/step - loss: 0.6236 - accuracy: 0.6500 - f1_metric: 0.1983
Epoch 3/150
10745/10745 [==============================] - 6s 605us/step - loss: 0.6206 - accuracy: 0.6287 - f1_metric: 0.0306
Epoch 4/150
10745/10745 [==============================] - 6s 605us/step - loss: 0.6220 - accuracy: 0.6278 - f1_metric: 0.1062
Epoch 5/150
10745/10745 [==============================] - 7s 606us/step - loss: 0.6208 - accuracy: 0.6341 - f1_metric: 0.0870
Epoch 6/150
10745/10745 [==============================] - 7s 605us/step - loss: 0.6089 - accuracy: 0.6622 - f1_metric: 0.2700
Epoch 7/150
10745/10745 [==============================] - 7s 624us/step - loss: 0.6119 - accuracy: 0.6560 - f1_metric: 0.3245
Epoch 8/150
10745/10745 [==============================] - 7s 617us/step - loss: 0.6101 - accuracy: 0.6632 - f1

10745/10745 [==============================] - 7s 628us/step - loss: 0.6066 - accuracy: 0.6664 - f1_metric: 0.2600
Epoch 66/150
10745/10745 [==============================] - 7s 628us/step - loss: 0.6061 - accuracy: 0.6506 - f1_metric: 0.3560
Epoch 67/150
10745/10745 [==============================] - 7s 631us/step - loss: 0.6058 - accuracy: 0.6652 - f1_metric: 0.2551
Epoch 68/150
10745/10745 [==============================] - 7s 627us/step - loss: 0.6057 - accuracy: 0.6687 - f1_metric: 0.2925
Epoch 69/150
10745/10745 [==============================] - 7s 626us/step - loss: 0.6073 - accuracy: 0.6566 - f1_metric: 0.2305
Epoch 70/150
10745/10745 [==============================] - 7s 628us/step - loss: 0.6042 - accuracy: 0.6652 - f1_metric: 0.3437
Epoch 71/150
10745/10745 [==============================] - 7s 638us/step - loss: 0.6043 - accuracy: 0.6669 - f1_metric: 0.3701
Epoch 72/150
10745/10745 [==============================] - 9s 818us/step - loss: 0.6044 - accuracy: 0.6576 - f1_metr

10745/10745 [==============================] - 7s 635us/step - loss: 0.6195 - accuracy: 0.6275 - f1_metric: 0.0254
Epoch 129/150
10745/10745 [==============================] - 7s 635us/step - loss: 0.6196 - accuracy: 0.6289 - f1_metric: 0.0214
Epoch 130/150
10745/10745 [==============================] - 7s 637us/step - loss: 0.6175 - accuracy: 0.6295 - f1_metric: 0.0034
Epoch 131/150
10745/10745 [==============================] - 7s 641us/step - loss: 0.6201 - accuracy: 0.6282 - f1_metric: 0.03500s - loss: 0.6201 - accuracy: 0.6282 - f
Epoch 132/150
10745/10745 [==============================] - 7s 656us/step - loss: 0.6179 - accuracy: 0.6294 - f1_metric: 0.0031
Epoch 133/150
10745/10745 [==============================] - 7s 649us/step - loss: 0.6182 - accuracy: 0.6293 - f1_metric: 0.0084
Epoch 134/150
10745/10745 [==============================] - 7s 641us/step - loss: 0.6180 - accuracy: 0.6295 - f1_metric: 0.0022
Epoch 135/150
10745/10745 [==============================] - 7s 636us/s

In [41]:
model.evaluate(X_test, y_test) # parameters were not tuned, so results are bad

374/374 [==============================] - 0s 652us/step - loss: 0.6143 - accuracy: 0.6286 - f1_metric: 0.0000e+00


[0.6142608523368835, 0.6286121010780334, 0.0]

In [53]:
model.predict(observation) # prediction

array([[0.47649106]], dtype=float32)

In [43]:
exp_nn = dx.Explainer(model, X_train, y_train, label='neural_network')

Preparation of a new explainer is initiated

  -> data              : 107447 rows 6 cols
  -> target variable   : Parameter 'y' was a pandas.DataFrame. Converted to a numpy.ndarray.
  -> target variable   : 107447 values
  -> model_class       : tensorflow.python.keras.engine.sequential.Sequential (default)
  -> label             : neural_network
  -> predict function  : <function yhat_tf_regression at 0x00000228ADDB3DC0> will be used (default)
  -> predict function  : Accepts pandas.DataFrame and numpy.ndarray.
  -> predicted values  : min = 0.157, mean = 0.378, max = 0.476
  -> model type        : regression will be used (default)
  -> residual function : difference between y and yhat (default)
  -> residuals         : min = -0.476, mean = -0.00776, max = 0.843
  -> model_info        : package tensorflow

A new explainer has been created!


In [50]:
nn_profile = exp_nn.predict_profile(new_observation = observation)

# plot Ceteris Paribus profile
nn_profile.plot(variables = ['lead_time', 'children', 'babies', 'booking_changes'])
# in this model chidren and babies variables did not matter at all
# bigger lead time(>81 days) increased probability of cancelation
# alternatively bigger number of booking changes decreased chances of clients not coming

Calculating ceteris paribus: 100%|███████████████████████████████████████████████████████| 6/6 [00:00<00:00, 24.33it/s]


## Random forest

In [51]:
forest = RandomForestClassifier(max_depth=2, random_state=0)
forest.fit(X_train, y_train)

RandomForestClassifier(max_depth=2, random_state=0)

In [52]:
forest.predict(observation) # prediction

array([0], dtype=int64)

In [54]:
exp_forest = dx.Explainer(forest, X_train, y_train, label='random_forest')

Preparation of a new explainer is initiated

  -> data              : 107447 rows 6 cols
  -> target variable   : Parameter 'y' was a pandas.DataFrame. Converted to a numpy.ndarray.
  -> target variable   : 107447 values
  -> model_class       : sklearn.ensemble._forest.RandomForestClassifier (default)
  -> label             : random_forest
  -> predict function  : <function yhat_proba_default at 0x00000228ADDB3C10> will be used (default)
  -> predict function  : Accepts pandas.DataFrame and numpy.ndarray.
  -> predicted values  : min = 0.139, mean = 0.37, max = 0.45
  -> model type        : classification will be used (default)
  -> residual function : difference between y and yhat (default)
  -> residuals         : min = -0.45, mean = -3.51e-05, max = 0.861
  -> model_info        : package sklearn

A new explainer has been created!


In [55]:
forest_profile = exp_forest.predict_profile(new_observation = observation)

# plot Ceteris Paribus profile
forest_profile.plot(variables = ['lead_time', 'children', 'babies', 'booking_changes'])

Calculating ceteris paribus: 100%|███████████████████████████████████████████████████████| 6/6 [00:00<00:00, 62.67it/s]


## AdaBoost

In [57]:
adaboost = AdaBoostClassifier(n_estimators=100, random_state=0)
adaboost.fit(X_train, y_train)

AdaBoostClassifier(n_estimators=100, random_state=0)

In [58]:
adaboost.predict(observation) # prediction

array([0], dtype=int64)

In [60]:
exp_adaboost = dx.Explainer(forest, X_train, y_train, label='adaboost')

Preparation of a new explainer is initiated

  -> data              : 107447 rows 6 cols
  -> target variable   : Parameter 'y' was a pandas.DataFrame. Converted to a numpy.ndarray.
  -> target variable   : 107447 values
  -> model_class       : sklearn.ensemble._forest.RandomForestClassifier (default)
  -> label             : adaboost
  -> predict function  : <function yhat_proba_default at 0x00000228ADDB3C10> will be used (default)
  -> predict function  : Accepts pandas.DataFrame and numpy.ndarray.
  -> predicted values  : min = 0.139, mean = 0.37, max = 0.45
  -> model type        : classification will be used (default)
  -> residual function : difference between y and yhat (default)
  -> residuals         : min = -0.45, mean = -3.51e-05, max = 0.861
  -> model_info        : package sklearn

A new explainer has been created!


In [61]:
adaboost_profile = exp_adaboost.predict_profile(new_observation = observation)

# plot Ceteris Paribus profile
adaboost_profile.plot(variables = ['lead_time', 'children', 'babies', 'booking_changes'])

Calculating ceteris paribus: 100%|███████████████████████████████████████████████████████| 6/6 [00:00<00:00, 65.07it/s]


## Summary